// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DummyProductV2$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DummyProductV2";
  readonly sourceName: "contracts/test/DummyProductV2.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"_initialValue","type":"uint256"}],"name":"initialize","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"newFeature","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"pure","type":"function"},{"inputs":[{"internalType":"uint256","name":"_newValue","type":"uint256"}],"name":"setValue","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"value","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"version","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x60808060405234601557610160908161001a8239f35b5f80fdfe6080806040526004361015610012575f80fd5b5f3560e01c908163274f0207146100f9575080633fa4f245146100dd57806354fd4d501461005857806355241077146100535763fe4b84df14610053575f80fd5b610112565b346100d9575f3660031901126100d957604080519081016001600160401b038111828210176100c5576040526005815260406020820191640322e302e360dc1b83528151928391602083525180918160208501528484015e5f828201840152601f01601f19168101030190f35b634e487b7160e01b5f52604160045260245ffd5b5f80fd5b346100d9575f3660031901126100d95760205f54604051908152f35b346100d9575f3660031901126100d95780600160209252f35b346100d95760203660031901126100d9576004355f5500fea26469706673582212201de40004fb1e3bd23e16b4f9b505e391a78bcb980644abfcbd1dcc23c63aa5ca64736f6c634300081c0033";
  readonly deployedBytecode: "0x6080806040526004361015610012575f80fd5b5f3560e01c908163274f0207146100f9575080633fa4f245146100dd57806354fd4d501461005857806355241077146100535763fe4b84df14610053575f80fd5b610112565b346100d9575f3660031901126100d957604080519081016001600160401b038111828210176100c5576040526005815260406020820191640322e302e360dc1b83528151928391602083525180918160208501528484015e5f828201840152601f01601f19168101030190f35b634e487b7160e01b5f52604160045260245ffd5b5f80fd5b346100d9575f3660031901126100d95760205f54604051908152f35b346100d9575f3660031901126100d95780600160209252f35b346100d95760203660031901126100d9576004355f5500fea26469706673582212201de40004fb1e3bd23e16b4f9b505e391a78bcb980644abfcbd1dcc23c63aa5ca64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/test/DummyProductV2.sol";
  readonly buildInfoId: "solc-0_8_28-57d4496aeb469bc0b0fcd772fce1d320cb11238d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DummyProductV2"]: DummyProductV2$Type;
    ["contracts/test/DummyProductV2.sol:DummyProductV2"]: DummyProductV2$Type;
  }
}