// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IUpgradeableBeacon$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IUpgradeableBeacon";
  readonly sourceName: "contracts/IUpgradeableBeacon.sol";
  readonly abi: [{"inputs":[],"name":"implementation","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"newImplementation","type":"address"}],"name":"upgradeTo","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IUpgradeableBeacon.sol";
  readonly buildInfoId: "solc-0_8_28-57d4496aeb469bc0b0fcd772fce1d320cb11238d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUpgradeableBeacon"]: IUpgradeableBeacon$Type;
    ["contracts/IUpgradeableBeacon.sol:IUpgradeableBeacon"]: IUpgradeableBeacon$Type;
  }
}