/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinTeamRouteImport } from './routes/join-team'
import { Route as CreateTeamRouteImport } from './routes/create-team'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIdSettingsRouteImport } from './routes/$teamId_.settings'
import { Route as TeamIdDocsRouteImport } from './routes/$teamId_.docs'
import { Route as TeamIdDashboardRouteImport } from './routes/$teamId_.dashboard'

const JoinTeamRoute = JoinTeamRouteImport.update({
  id: '/join-team',
  path: '/join-team',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTeamRoute = CreateTeamRouteImport.update({
  id: '/create-team',
  path: '/create-team',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdSettingsRoute = TeamIdSettingsRouteImport.update({
  id: '/$teamId_/settings',
  path: '/$teamId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdDocsRoute = TeamIdDocsRouteImport.update({
  id: '/$teamId_/docs',
  path: '/$teamId/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdDashboardRoute = TeamIdDashboardRouteImport.update({
  id: '/$teamId_/dashboard',
  path: '/$teamId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-team': typeof CreateTeamRoute
  '/join-team': typeof JoinTeamRoute
  '/$teamId/dashboard': typeof TeamIdDashboardRoute
  '/$teamId/docs': typeof TeamIdDocsRoute
  '/$teamId/settings': typeof TeamIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-team': typeof CreateTeamRoute
  '/join-team': typeof JoinTeamRoute
  '/$teamId/dashboard': typeof TeamIdDashboardRoute
  '/$teamId/docs': typeof TeamIdDocsRoute
  '/$teamId/settings': typeof TeamIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-team': typeof CreateTeamRoute
  '/join-team': typeof JoinTeamRoute
  '/$teamId_/dashboard': typeof TeamIdDashboardRoute
  '/$teamId_/docs': typeof TeamIdDocsRoute
  '/$teamId_/settings': typeof TeamIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-team'
    | '/join-team'
    | '/$teamId/dashboard'
    | '/$teamId/docs'
    | '/$teamId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-team'
    | '/join-team'
    | '/$teamId/dashboard'
    | '/$teamId/docs'
    | '/$teamId/settings'
  id:
    | '__root__'
    | '/'
    | '/create-team'
    | '/join-team'
    | '/$teamId_/dashboard'
    | '/$teamId_/docs'
    | '/$teamId_/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateTeamRoute: typeof CreateTeamRoute
  JoinTeamRoute: typeof JoinTeamRoute
  TeamIdDashboardRoute: typeof TeamIdDashboardRoute
  TeamIdDocsRoute: typeof TeamIdDocsRoute
  TeamIdSettingsRoute: typeof TeamIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join-team': {
      id: '/join-team'
      path: '/join-team'
      fullPath: '/join-team'
      preLoaderRoute: typeof JoinTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-team': {
      id: '/create-team'
      path: '/create-team'
      fullPath: '/create-team'
      preLoaderRoute: typeof CreateTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$teamId_/settings': {
      id: '/$teamId_/settings'
      path: '/$teamId/settings'
      fullPath: '/$teamId/settings'
      preLoaderRoute: typeof TeamIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$teamId_/docs': {
      id: '/$teamId_/docs'
      path: '/$teamId/docs'
      fullPath: '/$teamId/docs'
      preLoaderRoute: typeof TeamIdDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$teamId_/dashboard': {
      id: '/$teamId_/dashboard'
      path: '/$teamId/dashboard'
      fullPath: '/$teamId/dashboard'
      preLoaderRoute: typeof TeamIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateTeamRoute: CreateTeamRoute,
  JoinTeamRoute: JoinTeamRoute,
  TeamIdDashboardRoute: TeamIdDashboardRoute,
  TeamIdDocsRoute: TeamIdDocsRoute,
  TeamIdSettingsRoute: TeamIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
