// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DummyProductV1$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DummyProductV1";
  readonly sourceName: "contracts/test/DummyProductV1.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"_initialValue","type":"uint256"}],"name":"initialize","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"uint256","name":"_newValue","type":"uint256"}],"name":"setValue","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"value","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"version","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"pure","type":"function"}];
  readonly bytecode: "0x6080806040523460155761012c908161001a8239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c9081633fa4f2451460c95750806354fd4d50146047578063552410771460435763fe4b84df146043575f80fd5b60e0565b3460c5575f36600319011260c557604080519081016001600160401b0381118282101760b1576040526005815260406020820191640312e302e360dc1b83528151928391602083525180918160208501528484015e5f828201840152601f01601f19168101030190f35b634e487b7160e01b5f52604160045260245ffd5b5f80fd5b3460c5575f36600319011260c5576020905f548152f35b3460c557602036600319011260c5576004355f5500fea2646970667358221220ae165a89656058a0b13bd1061daf593dca038a4551a144163becf8aef69e8b4164736f6c634300081c0033";
  readonly deployedBytecode: "0x60808060405260043610156011575f80fd5b5f3560e01c9081633fa4f2451460c95750806354fd4d50146047578063552410771460435763fe4b84df146043575f80fd5b60e0565b3460c5575f36600319011260c557604080519081016001600160401b0381118282101760b1576040526005815260406020820191640312e302e360dc1b83528151928391602083525180918160208501528484015e5f828201840152601f01601f19168101030190f35b634e487b7160e01b5f52604160045260245ffd5b5f80fd5b3460c5575f36600319011260c5576020905f548152f35b3460c557602036600319011260c5576004355f5500fea2646970667358221220ae165a89656058a0b13bd1061daf593dca038a4551a144163becf8aef69e8b4164736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/test/DummyProductV1.sol";
  readonly buildInfoId: "solc-0_8_28-57d4496aeb469bc0b0fcd772fce1d320cb11238d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DummyProductV1"]: DummyProductV1$Type;
    ["contracts/test/DummyProductV1.sol:DummyProductV1"]: DummyProductV1$Type;
  }
}